# Generated by Django 4.2.5 on 2023-09-12 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peopleAPI', '0003_interns_delete_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interns',
            old_name='first_name',
            new_name='fullname',
        ),
        migrations.RemoveField(
            model_name='interns',
            name='last_name',
        ),
    ]
