# Generated by Django 4.2.5 on 2023-09-12 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peopleAPI', '0004_rename_first_name_interns_fullname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interns',
            name='stage',
        ),
    ]
