# Generated by Django 4.2.5 on 2023-09-12 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peopleAPI', '0005_remove_interns_stage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Interns',
            new_name='Person',
        ),
    ]
